---
- hosts: centos
  become: True
  tasks:
  - name: Install LAMP
    yum:
      name: '{{item}}'
      state: present
    with_items:
    - httpd
    - mariadb-server
    - mariadb
    - php
    - php-mysql
    - php-fpm

  - name: Ensure service enable and started
    service:
      name: '{{item}}'
      state: started
      enabled: True
    with_items:
    - mariadb
    - httpd

  - name: Ensure HTTP ans HTTPS can pass the firewall
    firewalld:
      service: '{{item}}'
      state: enabled
      permanent: True
      immediate: True
    become: True
    with_items:
    - http
    - https

  - name: Install php-dg, rsync
    yum:
      name: '{{item}}'
      state: present
    with_items:
    - php-gd
    - rsync

  - name: Restart httpd
    service:
      name: httpd
      state: restarted

  - name: Down wordpress
    get_url:
      url: http://wordpress.org/wordpress-5.3.2.tar.gz
      dest: /home/itc
  - name: extract WP
    unarchive:
      src: /home/wordpress-5.3.2.tar.gz
      dest: /home/itc
      remote_src: yes
      copy: no

  - name: rsync wordpress
    shell: rsync -avP /home/itc/wordpress/ /var/www/html/
#  - name: create folder uploads
#    shell: mkdir /var/www/html/wp-content/uploads
  - name: Set user:group
    shell: chown -R apache:apache /var/www/html/*

  - name: Install MySQL-python
    yum:
      name: MySQL-python
      state: present

  - name: Create DB wordpress
    mysql_db:
      name: wordpress
      state: present

  - name: Create User wpuser
    mysql_user:
      name: wpuser
      host: localhost
      password: wordpresspassword
      priv: 'wordpress.*:ALL'
      state: present

  - name: Backup file config wp
    shell: cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
  - name: config DB name
    replace:
      dest: /var/www/html/wp-config.php
      regexp: 'database_name_here'
      replace: 'wordpress'
  - name: config username
    replace:
      dest: /var/www/html/wp-config.php
      regexp: 'username_here'
      replace: 'wpuser'
  - name: config password
    replace:
      dest: /var/www/html/wp-config.php
      regexp: 'password_here'
      replace: 'wordpresspassword'

  - name: Config version PHP
    yum:
      name: '{{item}}'
      state: present
    with_items:
    - epel-release
    - yum-utils
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm

  - name: Config version PHP
    shell: yum-config-manager --enable remi-php72
  - name: Config version PHP
    yum:
      name: '{{item}}'
      state: present
    with_items:
    - php
    - php-common
    - php-opcache
    - php-mcrypt
    - php-cli
    - php-gd
    - php-curl
    - php-mysqlnd

  - name: Restart Apache
    service:
      name: httpd
      state: restarted
